### ISSUE TITLE
.into(res) only returns first column value instead of entire query

### ISSUE THREAD

**Issue by ikantthink** [JocaPC/express4-tedious#4]
https://github.com/JocaPC/express4-tedious/blob/920b9b3e47f3c72bb75bcdcc3c7c87d3bf694c90/index.js#L35

**Comment by MWaser** [comment]
Since you're presumably using FOR JSON PATH, this is correct behavior . . . .

**Comment by JocaPC** [comment]
Take a look at https://github.com/JocaPC/express4-tedious/blob/920b9b3e47f3c72bb75bcdcc3c7c87d3bf694c90/index.js#L31
this code will register a function that will be called on every row that is returned . `FOR JSON` splits output text to 2KB rows and return it as a single-column collection. This function will just take every chunk and write it into the output stream.
